version: '3'
services:
  front:
      container_name: front
      build:
        context: .dockerfiles
        dockerfile: DockerfileFrontend
      ports:
        - 8080:5173
      volumes:
        - ./front:/app
      command: 'npm run dev'
      depends_on:
        - back
  back:
      container_name: back
      build:
        context: .dockerfiles
        dockerfile: DockerfileBackend
      ports:
        - 8888:8888
      volumes:
        - ./back:/app
      command: 'composer startup'
      depends_on:
        - banco
      networks:
        - cadeletro
  banco:
      image: mysql:5.7
      container_name: banco
      ports:
        - '3306:3306'
      volumes:
        - ./banco:/var/lib/mysql
      environment:
        - MYSQL_DATABASE=cadeletro
        - MYSQL_ROOT_PASSWORD=cadeletro
        - MYSQL_USER=cadeletro
        - MYSQL_PASSWORD=cadeletro
      networks:
        - cadeletro
networks:
  cadeletro:
    driver: bridge