version: '3'
services:
  front:
      container_name: front
      build:
        context: .dockerfiles
        dockerfile: DockerfileFrontend
      ports:
        - 8080:5173
      volumes:
        - ./front:/app
      command: 'npm run dev'
      